export interface Topic {
  title: string;
  description: string;
}

export interface Chapter {
  number: string;
  label: string;
  title: string;
  subtitle: string;
  description: string;
  image: string;
  numberPosition: 'left' | 'right';
  topics: Topic[];
}

export const chapters: Chapter[] = [
  {
    number: '01',
    label: 'CHAPTER 01',
    title: 'The Sonic Blueprint',
    subtitle: 'Acoustics & Theory',
    description: 'Physics of sound, frequency, amplitude, phase, psychoacoustics, and critical listening—built for real-world decisions.',
    image: '/ch01_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'Physics of Sound', description: 'Longitudinal waves, compression, and rarefaction. Sound travels at 343 m/s in air at 20°C.' },
      { title: 'Frequency & Pitch', description: 'The relationship between f = 1/T and musical notes. A4 = 440 Hz. Octaves double the frequency.' },
      { title: 'Amplitude & Loudness', description: 'Understanding the Decibel (dB) scale and SPL. 3 dB = double power, 10 dB = perceived doubling.' },
      { title: 'The Harmonic Series', description: 'Fundamentals, overtones, and the physics of timbre. Why a violin sounds different from a trumpet.' },
      { title: 'Phase Relationships', description: 'Constructive vs. destructive interference and comb filtering. Critical for microphone placement.' },
      { title: 'Psychoacoustics', description: 'The Fletcher-Munson curves and equal-loudness contours. Mixing at 85 dB SPL for linear response.' },
      { title: 'Spatial Perception', description: 'Interaural Time Difference (ITD) and Intensity Difference (IID). Foundation for panning and stereo imaging.' },
      { title: 'The Haas Effect', description: 'Using precedence for depth and width. Delaying copies by 10-20ms creates spaciousness.' },
      { title: 'Room Modes', description: 'Standing waves, axial, tangential, and oblique modes. Why untreated rooms have uneven bass response.' },
      { title: 'Acoustic Treatment', description: 'Absorbers, diffusers, and bass traps. DIY vs. commercial solutions for neutral listening environments.' },
      { title: 'Critical Listening 1', description: 'Identifying Q factors and frequency bands by ear. Sub-bass to air frequencies (20 Hz - 20 kHz).' },
      { title: 'Critical Listening 2', description: 'Analyzing professional mixes for depth and width. Using analyzers to deconstruct reference tracks.' },
      { title: 'Advanced Rhythm Theory', description: 'Polyrhythms (3:4, 5:4) and polymeters. Creating complex, interlocking rhythmic feels.' },
      { title: 'The Circle of Fifths', description: 'Modulation techniques for electronic music. Pivot chords and chromatic mediants.' },
      { title: 'Microtonality', description: 'Exploring non-Western scales and xenharmonics. MPE and custom microtonal scales.' },
      { title: 'Ear Protection', description: 'Managing tinnitus and long-term auditory health. Musicians\' earplugs and the 3 dB rule.' },
      { title: 'Monitor Calibration', description: 'Setting up an 85 dB reference listening environment. The K-System standard by Bob Katz.' },
      { title: 'Subwoofer Integration', description: 'Crossover frequencies and phase alignment. Typical crossover at 80 Hz.' },
      { title: 'The Psychology of Sound', description: 'How specific frequencies trigger emotional responses. Sub-bass = power, air = spaciousness.' },
      { title: 'History of Audio', description: 'From wax cylinders (1877) to 32-bit float recording. Evolution of recording technology.' },
      { title: 'Studio Ergonomics', description: 'Cable management, lighting, and physical workflow. Creating a comfortable creative space.' },
      { title: 'Philosophy of Production', description: 'The "Commit Early" vs. "Infinite Options" mindset. Strategic use of both approaches.' },
    ],
  },
  {
    number: '02',
    label: 'CHAPTER 02',
    title: 'The DAW Ecosystem',
    subtitle: 'Infrastructure',
    description: 'Signal flow, gain staging, templates, MIDI, and the practical workflows that make a reliable studio.',
    image: '/ch02_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'Digital Audio Engine', description: 'Sample rates (44.1k to 192k) and bit depth. Nyquist-Shannon theorem and 32-bit float processing.' },
      { title: 'Buffer Size vs. Latency', description: 'Optimizing for recording vs. mixing. Small buffers (32-128) for tracking, large (512-2048) for mixing.' },
      { title: 'Signal Flow 101', description: 'Inputs, pre-fader vs. post-fader sends, and returns. Essential routing concepts.' },
      { title: 'Ableton Live Deep Dive', description: 'Session vs. Arrangement mastery. The dual-view architecture for improvisation and composition.' },
      { title: 'Pro Tools Deep Dive', description: 'The industry standard for editing and tracking. Tab to Transient, Elastic Audio, Beat Detective.' },
      { title: 'Logic Pro Deep Dive', description: 'Creative tools and the Environment. Drum Machine Designer, Alchemy, and MIDI FX plugins.' },
      { title: 'Template Architecture', description: 'Building "Instant-On" templates for various genres. Pre-routed tracks, FX returns, and color-coding.' },
      { title: 'File Management', description: 'Naming conventions, version control, and cloud backups. The 3-2-1 backup rule.' },
      { title: 'The MIDI Protocol', description: 'CC messages, velocity, aftertouch, and SysEx. Understanding MIDI communication.' },
      { title: 'MIDI Scripting', description: 'Customizing controller surfaces with Python/Remote Scripts. Creating personalized workflows.' },
      { title: 'MPE (MIDI Polyphonic Expression)', description: 'Working with Roli and LinnStrument. Per-note pitch bend, timbre, and volume control.' },
      { title: 'Max for Live (M4L)', description: 'Building custom devices and utilities. Visual programming for unique production tools.' },
      { title: 'Plugin Management', description: 'VST3, AU, and AAX architectures. Organizing plugins by type for efficient workflow.' },
      { title: 'CPU Optimization', description: 'Freezing tracks, oversampling, and multi-core handling. Managing processing power.' },
      { title: 'Gain Staging (Digital)', description: 'Maintaining headroom in a floating-point environment. Targeting -18 dBFS RMS.' },
      { title: 'Bussing & Sub-mixing', description: 'Creating stems for massive 100+ track projects. Organizational and processing benefits.' },
      { title: 'Sidechain Architecture', description: 'Beyond "The Pump"—creative utility routing. De-essing, spatial ducking, and frequency-specific sidechaining.' },
      { title: 'Automation Mastery', description: 'LFOs, envelopes, and macro mapping. Making mixes dynamic and alive.' },
      { title: 'Non-Linear Editing', description: 'Elastic Audio, Flex-time, and Warp Modes. Manipulating timing without affecting pitch.' },
      { title: 'The "Ghost" Track', description: 'Using MIDI triggers for invisible processing. Creating rhythmic pulses independent of kick drums.' },
      { title: 'VCA Groups', description: 'Managing complex arrangements with single faders. Controlling gain without routing audio.' },
      { title: 'Keyboard Shortcuts', description: 'Building muscle memory for high-speed production. Essential shortcuts for common actions.' },
      { title: 'External Gear Integration', description: 'Hardware inserts and latency compensation. Integrating outboard processors into DAW workflows.' },
      { title: 'Control Surfaces', description: 'Integrating Push, Maschine, and motorized faders. Tactile control for hands-on production.' },
      { title: 'Collaborative Workflow', description: 'Stem exchanges and Splice/Dropbox integration. Clear, organized file exchange for collaboration.' },
    ],
  },
  {
    number: '03',
    label: 'CHAPTER 03',
    title: 'Synthesis & Sound Design',
    subtitle: 'Advanced',
    description: 'Subtractive, wavetable, FM, granular, modular, and the art of building your signature sound.',
    image: '/ch03_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'Subtractive Synthesis', description: 'Oscillators, filters (LPF/HPF/BPF), and envelopes. The classic analog synthesis architecture.' },
      { title: 'Wavetable Synthesis', description: 'Table scanning and custom wavetable creation. Serum, Vital, and Waldorf Quantum.' },
      { title: 'FM Synthesis', description: 'Operators, algorithms, and the "bells to bass" spectrum. Yamaha DX7 and complex timbres.' },
      { title: 'Additive Synthesis', description: 'Building sounds from sine-wave partials. Harmor, Alchemy, and Kawai K5000.' },
      { title: 'Granular Synthesis', description: 'Grain size, spray, and textural "clouds." Granulator II, Quanta, and The Mangle.' },
      { title: 'Physical Modeling', description: 'Excitors and resonators. Virtual instrument architecture with AAS Chromaphone and Logic Sculpture.' },
      { title: 'Sample-Based Synthesis', description: 'Multi-sampling and velocity mapping in Kontakt. Creating realistic virtual instruments.' },
      { title: 'Modular Synthesis Theory', description: 'Control Voltage (CV), gates, and triggers. The patch cable philosophy of Eurorack.' },
      { title: 'Virtual Modular', description: 'Exploring VCV Rack and Bitwig\'s The Grid. Digital modular environments.' },
      { title: 'The Art of the "Layer"', description: 'Combining organic and synthetic textures. Building modern snares from multiple elements.' },
      { title: 'LFO Modulation', description: 'Creative syncopation and "wobble" architecture. Tempo-synced rhythmic effects.' },
      { title: 'Envelopes (ADSR)', description: 'Shaping transients and tails for punch. Attack, Decay, Sustain, Release fundamentals.' },
      { title: 'Filter Resonance', description: 'Self-oscillation and acidic sound design. The iconic Roland TB-303 "squelch."' },
      { title: 'Frequency vs. Pitch Shifters', description: 'Non-harmonic exploration. Creating metallic, dissonant textures.' },
      { title: 'Distortion & Saturation', description: 'Soft-clipping, bit-crushing, and excitement. Adding harmonics and perceived loudness.' },
      { title: 'The "Washed Out" Sound', description: 'Creative use of infinite-tail reverbs. Ambient, shoegaze, and lofi textures.' },
      { title: 'Resampling Workflow', description: 'Turning MIDI phrases into unique audio samples. Rendering and re-processing for unexpected results.' },
      { title: 'Vocoders & Talkboxes', description: 'The science of the human-synth hybrid. Daft Punk to Peter Frampton.' },
      { title: 'Field Recording', description: 'Capturing the world with portable recorders. Zoom H-series and Sound Devices MixPre.' },
      { title: 'Found Sound Processing', description: 'Turning a "kitchen sink" into a snare drum. Extreme processing of non-musical objects.' },
      { title: 'Synthesizing Percussion', description: 'Building kicks and hats from scratch. Sine waves with pitch envelopes for kicks.' },
      { title: 'Phase Plant & Architecture', description: 'Multi-engine hybrid synthesis. Combining multiple oscillator types in one framework.' },
      { title: 'Randomization', description: 'Generative sound design and controlled chaos. Sample & hold, random LFOs, and Markov chains.' },
      { title: 'Preset Management', description: 'Building a custom signature sound bank. Organization and creating your sonic identity.' },
      { title: 'UI/UX for Sound Design', description: 'Creating visually intuitive custom instruments. Macros, visual feedback, and logical layouts.' },
    ],
  },
  {
    number: '04',
    label: 'CHAPTER 04',
    title: 'Rhythmic Engineering',
    subtitle: 'Beat Making',
    description: 'Kick/snare relationship, layering, transient shaping, groove, and genre-focused production.',
    image: '/ch04_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'The Kick/Snare Relationship', description: 'Frequency slotting and phase alignment. Creating the foundation of rhythmic arrangements.' },
      { title: 'Drum Layering', description: 'Combining "thump," "knock," and "snap." Building composite drum hits from multiple samples.' },
      { title: 'Transient Shaping', description: 'Using sustain and attack to sit drums in a mix. Independent control of initial hit and body.' },
      { title: 'The "Pocket"', description: 'Micro-timing, swing, and manual quantization. Creating human feel and groove.' },
      { title: 'Ghost Notes', description: 'Adding "shuffle" and life to static loops. Low-velocity notes in 16th or 32nd note spaces.' },
      { title: 'The 808 Science', description: 'Tuning, gliding, and harmonic saturation. Making 808s audible on all speakers.' },
      { title: 'Breakbeat Chopping', description: 'Slicing, re-ordering, and "The Amen Break." The most sampled drum break in history.' },
      { title: 'Hybrid Drums', description: 'Blending live kits with electronic samples. Trigger 2 and Slate Trigger for drum replacement.' },
      { title: 'Trap/Hip-Hop Focus', description: 'High-hat rolls and triple-time flows. Complex 32nd and 64th note patterns.' },
      { title: 'House/Techno Focus', description: 'The 4-on-the-floor evolution and tension. Building energy through gradual introduction.' },
      { title: 'Lo-Fi Focus', description: 'Wow, flutter, and the beauty of "noise." RC-20 Retro Color and iZotope Vinyl emulation.' },
      { title: 'Cinematic/Epic Focus', description: 'Huge taikos and orchestral percussion. Power, scale, and emotional impact.' },
      { title: 'Polyrhythmic Beats', description: 'Creating hypnotic, shifting patterns. Layering conflicting time signatures.' },
      { title: 'Humanization', description: 'Velocity randomization and round-robin sampling. Avoiding the "machine-gun" effect.' },
      { title: 'Drum Buss Processing', description: 'Compression, saturation, and glue. VCA or SSL-style bus compression for cohesion.' },
      { title: 'Parallel Drum Crushing', description: 'The "New York Compression" technique. Blending heavily compressed signals with dry.' },
      { title: 'Sidechaining the Low End', description: 'Carving space between kick and bass. Dynamic EQ and multiband sidechaining.' },
      { title: 'The Art of the Fill', description: 'Transitions, rolls, and crashes. Drum rolls, cymbal accents, and risers.' },
      { title: 'Percussion Textures', description: 'Using foley as rhythmic "glue." Cloth rustling, paper crinkling for background texture.' },
      { title: 'Groove Extraction', description: 'Stealing the "feel" from classic records. Ableton\'s "Extract Groove" feature.' },
      { title: 'Sample Clearances', description: 'The ethics and legalities of sampling. Mechanical vs. master rights and fair use.' },
      { title: 'The "Drop" Architecture', description: 'Energy management and white noise sweeps. Build-ups, climaxes, and tension release.' },
      { title: 'Velocity Sensitivity', description: 'Creating expressive drum performances. Dynamic responses to playing force.' },
      { title: 'Multiband Drum Processing', description: 'Taming harsh cymbals while keeping punch. Independent control of frequency bands.' },
      { title: 'Building a Custom Kit', description: 'Curating your "go-to" drum library. Organizing favorites for immediate access.' },
    ],
  },
  {
    number: '05',
    label: 'CHAPTER 05',
    title: 'Audio Engineering',
    subtitle: 'Vocal Production',
    description: 'Mics, preamps, tracking, comping, pitch correction, and building a vocal that sits perfectly in the mix.',
    image: '/ch05_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'Microphone Types', description: 'Dynamic, condenser, ribbon, and tube. Shure SM57/58, Neumann U87, Royer R-121.' },
      { title: 'Polar Patterns', description: 'Cardioid, omni, figure-8, and the proximity effect. Understanding directional sensitivity.' },
      { title: 'Preamp Character', description: 'Solid state (clean) vs. tube (colored). Neve, API, Universal Audio, and Manley.' },
      { title: 'A/D Conversion', description: 'The importance of high-quality clocking. Avoiding jitter for pristine conversion.' },
      { title: 'Stereo Miking 1', description: 'XY and AB configurations. Intensity vs. time-of-arrival stereo imaging.' },
      { title: 'Stereo Miking 2', description: 'Mid-Side (M/S) and ORTF techniques. Adjustable width and natural stereo balance.' },
      { title: 'Vocal Tracking', description: 'Headphone mixes and "the vibe" in the booth. Psychology of great vocal performances.' },
      { title: 'Microphone Placement', description: 'For vocals, acoustic guitar, and piano. Distance, angle, and positioning techniques.' },
      { title: 'Room Bleed', description: 'Managing "bad" reflections during live takes. Gobos, close-miking, and isolation.' },
      { title: 'Vocal Comping', description: 'Selecting the "golden take" from multiple passes. Creating the perfect vocal from many takes.' },
      { title: 'Pitch Correction 1', description: 'Transparent tuning with Melodyne. Gentle correction and natural vibrato preservation.' },
      { title: 'Pitch Correction 2', description: 'The "hard tune" aesthetic (Auto-Tune). T-Pain effect with instant pitch correction.' },
      { title: 'Vocal Timing', description: 'Alignment tools (VocALign/Revoice Pro). Perfectly aligned doubles and harmonies.' },
      { title: 'De-Essing', description: 'Advanced sibilance control without "lisping." Spectral and split-band de-essing techniques.' },
      { title: 'Vocal Layering', description: 'Doubles, triples, and harmony stacks. Creating thickness and width with multiple takes.' },
      { title: 'The "Main Stage" Vocal', description: 'Compression chains for modern pop. Multi-stage compression for control and presence.' },
      { title: 'Background Vocals', description: 'EQ carving to sit "behind" the lead. Creating space and support without competition.' },
      { title: 'Vocal FX', description: 'Formant shifting, telephone filters, and delays. Creative effects for character and interest.' },
      { title: 'Breath Management', description: 'Editing vs. suppressing breaths for intimacy. Natural performance vs. clean production.' },
      { title: 'Coaching the Artist', description: 'The psychology of getting the best performance. Creating safe spaces and using direction.' },
      { title: 'Recording Mobile', description: 'Getting pro results in untreated hotel rooms. Dynamic mics and portable reflection filters.' },
      { title: 'DI Recording', description: 'Bass and guitar direct-injection techniques. Clean signals for re-amping later.' },
      { title: 'Amp Simulation', description: 'Using IRs (Impulse Responses) for realistic tone. Neural DSP, Guitar Rig, and third-party IRs.' },
      { title: 'Multi-mic Phase Alignment', description: 'Using plugins like Auto-Align. Achieving phase coherence for fuller sound.' },
      { title: 'The Vocal Producer\'s "Ear"', description: 'Knowing when a take is "the one." Recognizing emotional resonance and magic.' },
    ],
  },
  {
    number: '06',
    label: 'CHAPTER 06',
    title: 'The Art of the Mix',
    subtitle: 'Sculpting',
    description: 'EQ, compression, reverb, delay, depth, width, and the decisions that turn tracks into a record.',
    image: '/ch06_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'The First Move', description: 'Static mixing—balance and panning. Starting with faders before adding effects.' },
      { title: 'EQ 101', description: 'Subtractive EQ (cleaning) vs. additive EQ (coloring). Cut first, boost later philosophy.' },
      { title: 'Dynamic EQ', description: 'Taming frequencies only when they peak. Surgical, frequency-specific problems.' },
      { title: 'Compressors 1', description: 'VCA, FET, Opto, and Vari-Mu architectures. Different topologies, different sonic signatures.' },
      { title: 'Compressors 2', description: 'Threshold, ratio, attack, release, and knee. Understanding all compressor parameters.' },
      { title: 'Multiband Compression', description: 'Managing energy in specific bands. Independent compression of low, mid, and high frequencies.' },
      { title: 'Serial Compression', description: 'Using two compressors for smoother control. Fast peak catcher + smooth leveler.' },
      { title: 'Parallel Processing', description: 'Mixing the "dry" and "wet" for punch. Blending processed signals with original.' },
      { title: 'Saturation Artistry', description: 'Tape, tube, and transformer emulation. Adding harmonics, warmth, and glue.' },
      { title: 'Reverb Architecture', description: 'Room, hall, plate, and spring. Different reverb types for different spaces.' },
      { title: 'Convolution Reverb', description: 'Using real-world spaces via IRs. Placing sounds in specific acoustic environments.' },
      { title: 'Delay Strategies', description: 'Slapback, ping-pong, and ducking delays. Creative delay techniques for depth and rhythm.' },
      { title: 'Creating Depth', description: 'Using "darker" sounds to push things back. Frequency content and reverb for distance.' },
      { title: 'Creating Width', description: 'The Haas effect, micro-shifting, and mid-side. Stereo imaging techniques.' },
      { title: 'Mono Compatibility', description: 'Ensuring the mix doesn\'t disappear on a phone. Checking phase and center elements.' },
      { title: 'Frequency Slotting', description: 'Making sure every instrument has its own "home." EQ carving for separation.' },
      { title: 'Transient vs. Sustain', description: 'Balancing the "attack" of the whole mix. Punch vs. body considerations.' },
      { title: 'The Mix Bus', description: 'Subtle "glue" compression and EQ. SSL G Bus style processing for cohesion.' },
      { title: 'Automation', description: 'Riding faders for emotional dynamics. Creating builds, highlights, and energy arcs.' },
      { title: 'Reference Mixing', description: 'Using Metric AB to compare with pros. Objective analysis against professional tracks.' },
      { title: 'High-Pass Everything?', description: 'The myth vs. the reality of low-end mud. Contextual use of high-pass filters.' },
      { title: 'The "Breathe" Effect', description: 'Sidechaining the reverb to the vocal. Ducking reverb for clarity, blooming in gaps.' },
      { title: 'Mixing for Different Systems', description: 'Car, headphones, club, and phone. Ensuring translation across playback systems.' },
      { title: 'Top-Down Mixing', description: 'Starting with the master bus and working down. Making decisions that serve the final product.' },
      { title: 'Finishing the Mix', description: 'Knowing when to stop and walk away. Avoiding overworking and diminishing returns.' },
    ],
  },
  {
    number: '07',
    label: 'CHAPTER 07',
    title: 'Mastering & Delivery',
    subtitle: 'Final Polish',
    description: 'Objective listening, loudness standards, formats, metadata, and preparing your work for the world.',
    image: '/ch07_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'The Role of Mastering', description: 'Objective listening and final polish. Fresh perspective and technical quality control.' },
      { title: 'Linear Phase EQ', description: 'Correcting tone without phase shift. Broad tonal changes without smearing transients.' },
      { title: 'Mid-Side Mastering', description: 'Enhancing width and centering the low end. High-passing sides, boosting side highs.' },
      { title: 'Mastering Compression', description: 'Subtle "glue" (1-2 dB reduction). Vari-Mu and VCA bus compressors for cohesion.' },
      { title: 'Clipping vs. Limiting', description: 'The "loudness war" and soft-clipping. Transparent peak reduction techniques.' },
      { title: 'The "Wall of Sound"', description: 'Multiband limiting for maximum density. Independent limiting of frequency bands.' },
      { title: 'LUFS Standards', description: 'Targeting -14 (Spotify) vs. -9 (Club). Loudness normalization and platform-specific targets.' },
      { title: 'True Peak Limiting', description: 'Preventing inter-sample peaks. Ensuring -1 dBTP for streaming platforms.' },
      { title: 'Dithering', description: 'Moving from 32-bit to 24-bit or 16-bit. TPDF noise for bit-depth reduction.' },
      { title: 'Sample Rate Conversion', description: 'Downsampling without artifacts. High-quality SRC algorithms.' },
      { title: 'Stem Mastering', description: 'Getting more control than a single stereo file. Subgroups for targeted processing.' },
      { title: 'Metadata & ISRC', description: 'Embedding the hidden data in your music. International Standard Recording Codes.' },
      { title: 'Vinyl Mastering', description: 'Managing sibilance and low-end phase for wax. Physical medium constraints.' },
      { title: 'Cassette Mastering', description: 'Working with tape hiss and saturation. Embracing limitations for lo-fi aesthetics.' },
      { title: 'The "Mastering Ear"', description: 'Detecting subtle clicks, pops, and errors. Final quality control inspection.' },
      { title: 'Reference Metering', description: 'Using vectorscopes and LUFS meters. Visual analysis of stereo phase and loudness.' },
      { title: 'Dynamic Range Management', description: 'Preserving "punch" while being loud. Finding the sweet spot for impact.' },
      { title: 'Final QC', description: 'The 3-point check system. Visual, studio, and real-world auditory checks.' },
      { title: 'Exporting for Video', description: 'Handling the 48k standard. Delivering for film, TV, and broadcast.' },
      { title: 'Album Flow', description: 'Gapless transitions and consistent levels. Creating cohesive listening experiences.' },
      { title: 'Mastering for Radio', description: 'Understanding the "broadcast limiter." Avoiding over-compression for radio processing.' },
      { title: 'AI Mastering', description: 'Exploring Ozone and Landr (pros and cons). Automated vs. human mastering comparison.' },
      { title: 'DIY vs. Professional', description: 'When to hire a dedicated mastering engineer. World-class rooms and objective ears.' },
      { title: 'Headroom Management', description: 'Preparing your mix for a mastering pro. Leaving -6 to -3 dBFS peaks.' },
      { title: 'The "Air" Band', description: 'Mastering the 20-40 kHz spectrum. Ultrasonic frequencies for high-resolution formats.' },
    ],
  },
  {
    number: '08',
    label: 'CHAPTER 08',
    title: 'Live Performance',
    subtitle: 'Multi-Media',
    description: 'Hybrid sets, live looping, controllerism, visuals, lighting, and translating studio work to the stage.',
    image: '/ch08_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'The Hybrid Set', description: 'Blending DAW playback with live instruments. Seamless integration of backing tracks and performance.' },
      { title: 'Ableton Live for Performance', description: 'Using scenes and follow actions. Non-linear, grid-based live performance.' },
      { title: 'Live Looping 101', description: 'Building a track from scratch in real-time. Layering loops on the fly.' },
      { title: 'The Live Rig', description: 'Audio interfaces, MIDI hubs, and fail-safes. Reliable computer-based performance setup.' },
      { title: 'Redundancy', description: 'Building a "Play-B" system for stage failures. Backup computers and playback systems.' },
      { title: 'Stage Monitoring', description: 'In-ear monitors (IEMs) vs. wedges. Isolation, control, and hearing protection.' },
      { title: 'Controllerism', description: 'Mastery of Ableton Push or Novation Launchpad. Grid controllers as primary instruments.' },
      { title: 'External Hardware Sync', description: 'Keeping synths and drum machines in time. MIDI clock and CV/gate synchronization.' },
      { title: 'Live Audio Processing', description: 'Running vocals through DAW FX on stage. Studio-quality effects in live settings.' },
      { title: 'Visual Integration', description: 'Introduction to TouchDesigner for live visuals. Interactive, real-time visual programming.' },
      { title: 'Kinetic Typography', description: 'Syncing text animations with live vocals. Resolume and TouchDesigner for lyrics.' },
      { title: 'MIDI-to-Light', description: 'Controlling DMX lights via your DAW. Triggering lighting cues from MIDI notes.' },
      { title: 'The "Laptop Musician"', description: 'Aesthetics and stage presence. Moving beyond the screen to engage audiences.' },
      { title: 'Building a Setlist', description: 'Energy mapping and BPM transitions. Planning the arc of a live show.' },
      { title: 'Live Improv', description: 'Setting up "safe zones" for experimentation. Dedicated areas for spontaneous creativity.' },
      { title: 'Latency in Live Sets', description: 'Managing plugin heavy sessions on stage. Small buffers and low-latency plugins.' },
      { title: 'The Footswitch Workflow', description: 'Hands-free looping and FX toggling. MIDI foot controllers for performance.' },
      { title: 'Spatial Audio for Live', description: 'Using L-ISA or 4DSOUND systems. 3D audio placement around the audience.' },
      { title: 'Recording the Live Set', description: 'Capturing the "board mix" vs. multitrack. Post-produced live albums.' },
      { title: 'Stage Management', description: 'Communicating with FOH engineers. Tech riders, soundchecks, and professional relationships.' },
      { title: 'Touring Tech', description: 'Travel-friendly rigs and international power. Rugged cases and voltage compatibility.' },
      { title: 'Interactive Art', description: 'Using sensors to trigger sound. Leap Motion, Kinect, and body tracking for performance.' },
      { title: 'Web-Streaming Live', description: 'Setting up OBS for high-quality audio streams. ASIO routing and scene management.' },
      { title: 'The Live "Visualizer"', description: 'Creating reactive graphics for YouTube sets. MilkDrop, Plane9, and TouchDesigner.' },
      { title: 'Post-Show Analysis', description: 'Evaluating recordings to improve the set. Timing, mixing, pacing, and technical review.' },
    ],
  },
  {
    number: '09',
    label: 'CHAPTER 09',
    title: 'Modern Innovation',
    subtitle: 'AI & Spatial Audio',
    description: 'AI stem separation, generative tools, Dolby Atmos, binaural mixing, and staying human while using tech.',
    image: '/ch09_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'AI Stem Separation', description: 'Using Lalal.ai or RX for remixing. Machine learning isolation of vocals, drums, bass, and other.' },
      { title: 'AI Composition', description: 'Exploring MIDI generation tools. AIVA, Orb Composer, and Scaler 2 for creative sparks.' },
      { title: 'Vocal Transformation', description: 'Using AI for "voice conversion" (RVC). Retrieval-based voice conversion technology.' },
      { title: 'AI Mixing Assistants', description: 'Evaluating Neutron and Gullfoss. AI-powered mixing suites and intelligent EQ.' },
      { title: 'Generative Audio', description: 'Building "infinite" ambient tracks. Algorithmic systems that never repeat.' },
      { title: 'Spatial Audio: Dolby Atmos', description: 'Introduction to the 7.1.4 workflow. Object-based 3D audio placement.' },
      { title: 'Binaural Mixing', description: 'Immersive audio for standard headphones. HRTF-based 3D spatialization.' },
      { title: 'The Metaverse & Music', description: 'Virtual concerts and digital avatars. Fortnite, Roblox, and virtual performances.' },
      { title: 'Blockchain for Producers', description: 'NFTs and decentralized streaming. New models for music distribution and ownership.' },
      { title: 'Custom Tool Building', description: 'Using Python for batch audio processing. pydub, librosa, and soundfile automation.' },
      { title: 'Neural Networks in Synthesis', description: 'Synplant 2 and the "DNA" of sound. Genetically generated synth patches.' },
      { title: 'Remote Collaboration', description: 'Audiomovers and real-time studio linking. High-quality streaming to collaborators worldwide.' },
      { title: 'Cloud-Based Production', description: 'Splice, BandLab, and the future of DAWs. Online creation and collaboration.' },
      { title: 'The Ethics of AI', description: 'Copyright and the "deepfake" vocal debate. Ownership, consent, and human artistry.' },
      { title: 'Adaptive Music for Games', description: 'Using FMOD and Wwise. Middleware for interactive, non-linear music systems.' },
      { title: 'AI Lyric Generation', description: 'Using LLMs to break writer\'s block. ChatGPT and dedicated lyric-writing tools.' },
      { title: 'Smart Sample Management', description: 'Using Sononym or Atlas for AI sorting. Machine learning-based sample organization.' },
      { title: 'VR Audio', description: '6DOF (Degrees of Freedom) sound design. Full 3D spatialization for virtual reality.' },
      { title: 'Algorithmic Remixing', description: 'DAWs that "re-arrange" your track. Follow Actions and probability-based generation.' },
      { title: 'The Future of Hardware', description: 'Tactile AI controllers. Hardware interfaces for AI composition parameters.' },
      { title: 'Synthesizing Emotion', description: 'Neural analysis of "hit" melodies. Pattern recognition for emotional response prediction.' },
      { title: 'Automated Mastering', description: 'Is it taking over? Deep comparison of AI vs. human mastering approaches.' },
      { title: 'Web MIDI & Audio API', description: 'Building instruments in the browser. Browser-based synthesizers and DAWs.' },
      { title: 'AI-Driven Soundscapes', description: 'For sleep, focus, and therapy. Personalized, adaptive ambient generation.' },
      { title: 'Staying Human', description: 'Balancing tech innovation with raw creativity. Using AI as a tool, not a replacement.' },
    ],
  },
  {
    number: '10',
    label: 'CHAPTER 10',
    title: 'The Business',
    subtitle: 'Portfolio & Career',
    description: 'Sonic branding, pitching, copyright, royalties, sync, and building a sustainable practice.',
    image: '/ch10_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'Finding Your Signature', description: 'Building a "sonic brand." Recognizable production style and unique sound identity.' },
      { title: 'Portfolio Building', description: 'The "3-track rule" for pitching. Hit, vibe, and deep cut selections.' },
      { title: 'Networking', description: 'How to talk to A&Rs and creative directors. Building genuine relationships professionally.' },
      { title: 'Copyright Law', description: 'Work-for-hire vs. ownership. Composition and master recording copyrights.' },
      { title: 'Publishing 101', description: 'Royalties, splits, and PROs (BMI/ASCAP). Performance and mechanical royalties.' },
      { title: 'Music for Sync', description: 'Pitching to TV, film, and advertisements. Music supervisors and sync libraries.' },
      { title: 'Content Creation', description: 'Using social media to promote your sound. TikTok, Reels, and authentic engagement.' },
      { title: 'The "Producer" Contract', description: 'What to look for before signing. Scope, payment, credit, and rights.' },
      { title: 'Ghost Producing', description: 'The pros, cons, and the "silent" industry. Working in the shadows.' },
      { title: 'Building a Label', description: 'Logistics of digital distribution. DistroKid, Tunecore, and independent releases.' },
      { title: 'Freelancing', description: 'Using Fiverr/Upwork for engineering services. Global client access and platform considerations.' },
      { title: 'Studio Monetization', description: 'Renting out your space vs. your time. Passive income and client management.' },
      { title: 'Brand Partnerships', description: 'Working with plugin and hardware companies. Affiliate marketing and endorsements.' },
      { title: 'Tax for Musicians', description: 'Managing expenses and home offices. Business deductions and professional consultation.' },
      { title: 'The Pitch Deck', description: 'Creating a professional presentation. Bio, music, visuals, accomplishments, and goals.' },
      { title: 'YouTube for Producers', description: 'Education, beat-selling, and tutorials. Building authority and monetization.' },
      { title: 'Community Building', description: 'Discord and Patreon strategies. Direct fan engagement and subscription support.' },
      { title: 'Handling Rejection', description: 'The psychology of the music industry. Persistence and resilience as key skills.' },
      { title: 'Diversifying Income', description: 'Merch, sample packs, and presets. Multiple revenue streams for sustainability.' },
      { title: 'Project Management', description: 'Using Trello or Notion for album cycles. Organizing tasks and tracking progress.' },
      { title: 'Mental Health', description: 'Managing burnout and creative blocks. Self-care and maintaining creative longevity.' },
      { title: 'The Global Market', description: 'Producing for diverse regional markets. K-pop, Afrobeats, and Latin trap opportunities.' },
      { title: 'Publicity (PR)', description: 'When to hire a publicist for your release. DIY vs. professional PR campaigns.' },
      { title: 'Legacy Building', description: 'Archiving your work for the future. Long-term backups and physical media.' },
      { title: 'The Exit Strategy', description: 'Moving from producer to executive or teacher. Career evolution and transferable skills.' },
    ],
  },
  {
    number: '11',
    label: 'CHAPTER 11',
    title: 'The Creative Engine',
    subtitle: 'Songwriting & Psychology',
    description: 'Hooks, arrangement arcs, creative constraints, collaboration, and finishing songs.',
    image: '/ch11_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'The "Big Idea"', description: 'Identifying the core hook first. Finding the anchor element for the entire track.' },
      { title: 'Modern Song Structures', description: 'Verse-chorus-bridge vs. electronic "journey." Pop structure and fluid electronic arrangements.' },
      { title: 'The Psychology of the "Blank Canvas"', description: 'Overcoming paralysis. Templates, constraints, and starting strategies.' },
      { title: 'Top-Lining Mastery', description: 'Writing melodies that stick. Melodic contour, repetition with variation, and syncopation.' },
      { title: 'Lyric Writing for Producers', description: 'Helping vocalists refine messages. Identifying themes and focusing on imagery.' },
      { title: 'Arrangement Arcs', description: 'Managing energy over 3–5 minutes. Tension, release, and contrast mapping.' },
      { title: 'The "Finish the Song" Intervention', description: 'Escaping the 8-bar loop. Copy-paste, structure by subtraction, and working backwards.' },
      { title: 'Collaborative Etiquette', description: 'Managing egos in the room. Mutual respect and positive reinforcement.' },
      { title: 'Vocal Arrangement', description: 'Writing harmonies and ad-libs. Doubles, triples, and harmony stacks.' },
      { title: 'Genre-Blending Theory', description: 'Injecting jazz into trap or folk into techno. Cross-genre harmonic and rhythmic concepts.' },
      { title: 'The "Subtracting" Technique', description: 'Deleting layers to save a song. Creating clarity through removal.' },
      { title: 'Reference Track Anatomy', description: 'Breaking down a hit\'s timeline. Instrumentation, energy, and effects analysis.' },
      { title: 'Creative Constraints', description: 'Using limitations to spark innovation. Track limits, single synths, and unusual time signatures.' },
      { title: 'The "Second-Half" Evolution', description: 'Keeping listeners engaged. New elements in the second half of arrangements.' },
      { title: 'Ear Candy', description: 'Subtle sounds that keep a mix fresh. One-off effects and sonic surprises.' },
      { title: 'Bridge/Breakdown Mastery', description: 'Creating emotional pivots. Harmonic shifts and textural changes.' },
      { title: 'Frequency vs. Emotion', description: 'Which instrument ranges trigger feelings? Sub-bass = power, highs = clarity.' },
      { title: 'The Producer\'s "Vibe"', description: 'Setting the physical atmosphere. Lighting, space, and positive attitude.' },
      { title: 'Objective Self-Review', description: 'Judging your own work without bias. Time away, reference tracks, and peer feedback.' },
      { title: 'Tempo & Key Psychology', description: 'Emotional impact of BPM and key. Fast = energy, slow = introspection.' },
      { title: 'The "Wall" & How to Break It', description: 'Dealing with creative blocks. Changing process, learning new things, consuming art.' },
      { title: 'Storytelling Through Sound', description: 'Creating narrative arcs. Sound design and arrangement as storytelling tools.' },
      { title: 'Demoitis', description: 'Avoiding getting too attached to rough drafts. Embracing the evolution to final versions.' },
      { title: 'The Art of the "Outro"', description: 'Giving a reason to loop the song. Fade outs, stem removal, and held chords.' },
      { title: 'Creative Longevity', description: 'Staying inspired for 15+ years. Curiosity, change, and life outside music.' },
    ],
  },
  {
    number: '12',
    label: 'CHAPTER 12',
    title: 'Sound for Visual Media',
    subtitle: 'Film & Games',
    description: 'Foley, ADR, adaptive music, middleware, and designing sound that serves the story.',
    image: '/ch12_bg.jpg',
    numberPosition: 'left',
    topics: [
      { title: 'Linear vs. Non-Linear Audio', description: 'Film vs. games. Fixed timelines vs. interactive, reactive audio systems.' },
      { title: 'The Foley Stage', description: 'Recording everyday objects for SFX. Footsteps, cloth, doors, and props in sync with picture.' },
      { title: 'ADR (Automated Dialogue Replacement)', description: 'Syncing dialogue in post. Re-recording vocals to replace unusable location audio.' },
      { title: 'Ambient Bed Design', description: 'Creating "room tone" and textures. Layering field recordings for environmental atmosphere.' },
      { title: 'Soundscapes for VR', description: 'Managing 360-degree audio. Ambisonics and game engine spatialization.' },
      { title: 'Wwise & FMOD Integration', description: 'Game audio middleware. Bridging audio content and game engines.' },
      { title: 'Adaptive Music', description: 'Music that changes based on player actions. Horizontal re-sequencing and vertical layering.' },
      { title: 'The "Spotting" Session', description: 'Deciding where music goes in a film. Director, supervisor, and composer collaboration.' },
      { title: 'Sound Design for Logos', description: 'Creating "sonic brands." Short, memorable audio identities like THX and Netflix.' },
      { title: 'Cinematic Impact', description: 'Designing braams and risers. Low-end impacts and tension-building sweeps.' },
      { title: 'Syncing to Picture', description: 'Frame rates and SMPTE timecodes. 24 fps, 25 fps, 29.97 fps synchronization.' },
      { title: 'Dialogue Cleaning', description: 'Removing wind and background noise. iZotope RX spectral repair and de-noising.' },
      { title: 'Walladrops & Crowds', description: 'Simulating group environments. Layering voices to create large crowd reactions.' },
      { title: 'Impact Engineering', description: 'Making explosions feel visceral. Sub hits, ripping metal, and debris composites.' },
      { title: 'Music for Commercials', description: 'High-impact ideas in 30 seconds. Structured arcs for brand messaging.' },
      { title: 'Stem Delivery for Film', description: 'Organizing files for re-recording mixers. Music stems for final dub control.' },
      { title: 'Dynamic Range for Cinema', description: 'Mastering for theater vs. mobile. Enormous dynamic range for immersive experiences.' },
      { title: 'SFX Libraries', description: 'Managing and tagging thousands of samples. Metadata and search tools like Soundminer.' },
      { title: 'Synthesizing Sci-Fi', description: 'Futuristic tech sounds. Lasers, interfaces, and alien voices.' },
      { title: 'Emotional Underscoring', description: 'Using minimalism for mood. Sustained strings and sparse piano for tension.' },
      { title: 'Leitmotif Theory', description: 'Character-specific musical themes. Wagner and John Williams-style recurring motifs.' },
      { title: 'Pitching to Music Supervisors', description: 'Getting on Netflix/HBO. Building relationships and curated submissions.' },
      { title: 'Legal of "Sound-alikes"', description: 'When brands want "like a hit." Navigating inspiration vs. copyright infringement.' },
      { title: 'Orchestral Hybridization', description: 'Blending strings with synths. Modern film score sound with sub-bass and pads.' },
      { title: 'Post-Production Workflow', description: 'Meeting tight deadlines. Templates, asset management, and stability.' },
    ],
  },
  {
    number: '13',
    label: 'CHAPTER 13',
    title: 'Physical Infrastructure',
    subtitle: 'Studio Build',
    description: 'Floorplans, power, grounding, acoustic treatment, cable management, and ergonomics.',
    image: '/ch13_bg.jpg',
    numberPosition: 'right',
    topics: [
      { title: 'Studio Floorplans', description: 'Designing for workflow and acoustics. The monitoring triangle and room symmetry.' },
      { title: 'Electrical Foundations', description: 'Clean power and grounding. Dedicated circuits and star grounding for noise reduction.' },
      { title: 'Power Conditioning', description: 'Protecting gear from surges. Furman and APC for surge protection and noise filtering.' },
      { title: 'The Soldering Iron 101', description: 'Building custom cables. XLR, TRS, and TS soldering techniques.' },
      { title: 'Custom Patchbay Logic', description: 'Designing an analog matrix. Normal, half-normal, and open configurations.' },
      { title: 'Acoustic Panel Construction', description: 'DIY bass traps. Owens Corning 703, Rockwool, and fabric wrapping.' },
      { title: 'Studio Lighting Psychology', description: 'Using RGB for mood. Color temperature, dimmable lights, and creative atmosphere.' },
      { title: 'Rack Management', description: 'Thermal cooling and placement. Heavy gear at bottom, cooling space, and cable management.' },
      { title: 'Computer Hardware for Audio', description: 'Building vs. buying. Fast processors, ample RAM, silent cooling, and SSDs.' },
      { title: 'Storage Solutions', description: 'RAID arrays and NAS systems. Redundancy, performance, and networked storage.' },
      { title: 'Networking for Audio', description: 'Dante and AVB protocols. Audio-over-IP for low latency and high channel counts.' },
      { title: 'Custom Studio Furniture', description: 'Designing the perfect desk. Ergonomics, rack spaces, and monitor shelves.' },
      { title: 'Mobile Rig Design', description: 'Studio-in-a-box for travel. Compact, self-contained, and durable portable setups.' },
      { title: 'Instrument Maintenance', description: 'Caring for synths and drums. Dust covers, battery replacement, and tuning.' },
      { title: 'Microphone Storage', description: 'Humidity control. Hard cases, dehumidifiers, and dry cabinets for capsule protection.' },
      { title: 'Cable Topography', description: 'Balanced vs. unbalanced theory. XLR/TRS for long runs, TS/RCA for short connections.' },
      { title: 'The "Silent" Studio', description: 'Building vocal booths. Room-within-a-room design and silent ventilation.' },
      { title: 'Monitor Placement Geometry', description: 'The equilateral triangle. Ear height, toe-in, and proper listening position.' },
      { title: 'Multi-Computer Setups', description: 'Using Vienna Ensemble Pro. Distributing CPU load across networked computers.' },
      { title: 'Troubleshooting 101', description: 'Systematic signal path checking. Power, cables, connections, and multimeter testing.' },
      { title: 'Hardware Calibration', description: 'Keeping gear at 0 VU. +4 dBu/-18 dBFS alignment for optimal headroom.' },
      { title: 'The DIY Synthesizer', description: 'Intro to soldering synth kits. Synthrotek, Befaco, and hands-on electronics learning.' },
      { title: 'Studio Safety', description: 'Fire prevention and hearing health. Circuit management and decibel monitoring.' },
      { title: 'Ergonomic Health', description: 'Standing desks and wrist health. Preventing back pain and carpal tunnel syndrome.' },
      { title: 'The "Dream Studio" Roadmap', description: 'Upgrading to commercial space. Acoustic design, isolation, and business planning.' },
    ],
  },
];

export const dspMathTopics: Topic[] = [
  { title: 'Nyquist-Shannon Theorem', description: 'Why f_s > 2 * f_max. The fundamental principle of digital audio sampling.' },
  { title: 'Quantization & Bit Depth', description: 'Dynamic range (6 dB per bit). Mapping analog amplitude to discrete digital values.' },
  { title: 'Aliasing & Anti-Aliasing', description: 'Fold-back frequencies. Preventing distortion with steep low-pass filters.' },
  { title: 'Sampling Theory', description: 'Impulse trains and reconstruction. Mathematical modeling of the sampling process.' },
  { title: 'Fixed vs. Floating-Point', description: '32-bit internal processing. Scientific notation for huge dynamic range.' },
  { title: 'Fourier Transform (FFT)', description: 'Time-domain to frequency-domain. Spectrum analyzers and spectral processing.' },
  { title: 'Spectral Leakage & Windowing', description: 'Hanning and Hamming windows. Tapering audio segments for accurate analysis.' },
  { title: 'Z-Transform Theory', description: 'Z-plane and digital filter design. Poles and zeros determining frequency response.' },
  { title: 'FIR Filters', description: 'Linear phase and coefficients. Finite Impulse Response for phase preservation.' },
  { title: 'IIR Filters', description: 'Feedback loops and poles/zeros. Infinite Impulse Response for sharp cutoffs.' },
  { title: 'Biquad Filter Topologies', description: 'LP, HP, and shelving math. The workhorse 2nd-order filter architecture.' },
  { title: 'Zero-Delay Feedback (ZDF)', description: 'Emulating analog filters. Solving feedback loops without sample delay.' },
  { title: 'Convolution Logic', description: 'Multiplication-and-addition for IRs. Applying acoustic characteristics via impulse responses.' },
  { title: 'Delay Line Theory', description: 'Integer vs. fractional delays. Interpolation for precise phase alignment.' },
  { title: 'Phase Vocoding', description: 'FFT-based time-stretching logic. Complex warping while maintaining phase coherence.' },
  { title: 'Waveshaping', description: 'Chebyshev polynomials for harmonics. Mathematical distortion for predictable overtones.' },
  { title: 'Dynamics Detection', description: 'Math of peak vs. RMS vs. VU. Different metering standards and their calculations.' },
  { title: 'Envelope Following', description: 'Attack/release coefficients (τ = RC). RC circuit modeling in digital envelope followers.' },
  { title: 'Look-ahead Logic', description: 'Circular buffers for limiting. Preventing overshoot with delayed analysis.' },
  { title: 'Dithering & Noise Shaping', description: 'Using TPDF to hide error. Decorrelating quantization error from signal.' },
  { title: 'Oversampling Mastery', description: 'Reducing high-frequency cramping. Processing at higher internal sample rates.' },
  { title: 'Phase Correlation', description: 'Trig for stereo imaging. Cross-correlation of left and right signals.' },
  { title: 'All-pass Filters', description: 'Phase manipulation and decorrelation. Frequency-dependent phase shifts.' },
  { title: 'Feedback Delay Networks', description: 'Algorithmic reverb architecture. Creating dense, smooth decay tails.' },
  { title: 'Pitch Detection Algorithms', description: 'Autocorrelation and YIN. Finding fundamental frequency through signal analysis.' },
  { title: 'SIMD & Optimization', description: 'Writing code for modern CPUs. Single Instruction, Multiple Data parallelism.' },
  { title: 'Buffer Management', description: 'Minimizing CPU jitter. Stable processing within buffer time constraints.' },
  { title: 'Sample Rate Conversion', description: 'Polyphase filters for downsampling. High-quality SRC algorithms.' },
  { title: 'Neural DSP Inference', description: 'Weights and processing in RVC/NAM. Running trained networks for audio modeling.' },
  { title: 'Physical Modeling Math', description: 'Solving the wave equation. Numerical simulation of vibrating objects.' },
];
